[package]
name = "twilight-cache-any-backend"
version = "0.13.0"
authors = ["lara <laralove143@icloud.com>"]
edition = "2021"
description = "A backend-agnostic Discord cache implementation for the Twilight ecosystem."
repository = "https://github.com/laralove143/twilight-cache-any-backend/"
license = "ISC"
keywords = ["discord", "discord-api", "twilight"]
categories = ["api-bindings", "asynchronous", "caching"]

[dependencies]
twilight-model = "0.13"
twilight-util = { version = "0.13", features = ["permission-calculator"] }
async-trait = "0.1"
thiserror = "1.0"
time = "0.3"